import localFont from "next/font/local";
import { Outfit } from "next/font/google";
import "./globals.css";
import Header from "./_components/Header";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

const outfit = Outfit({ subsets: ['latin'] })

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  //TODO: remember this came from the body tag:
  // className={`${geistSans.variable} ${geistMono.variable} antialiased`}
  return (
    <html lang="en" className={outfit.className}>
      <body>
        <div className="md:px-20">
          {<Header />}
          {children}
        </div>

        <div>

        </div>
      </body>
    </html>
  );
}
